# Generated by Django 3.1.2 on 2020-10-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201028_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
